Internal Server Error: /words_list
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\andre\PycharmProjects\xxxl\training\mainapp\views.py", line 26, in wordlist
    return render(request, 'wrdlist.html', sp)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\backends\django.py", line 103, in render
    context = make_context(
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\context.py", line 291, in make_context
    raise TypeError(
TypeError: context must be a dict rather than tuple.
"GET /words_list HTTP/1.1" 500 81050
Internal Server Error: /words_list
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\andre\PycharmProjects\xxxl\training\mainapp\views.py", line 31, in wordlist
    return render(request, 'wrdlist.html', {'sp': sp_norm})
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'i[0]'
"GET /words_list HTTP/1.1" 500 184544
Internal Server Error: /words_list
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\andre\PycharmProjects\xxxl\training\mainapp\views.py", line 31, in wordlist
    return render(request, 'wrdlist.html', {'spk': sp_norm})
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'i[0]'
"GET /words_list HTTP/1.1" 500 184558
Internal Server Error: /words_list
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\andre\PycharmProjects\xxxl\training\mainapp\views.py", line 31, in wordlist
    return render(request, 'wrdlist.html', {'spk': sp_norm})
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'i[0]'
"GET /words_list HTTP/1.1" 500 184558
Internal Server Error: /words_list
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\andre\PycharmProjects\xxxl\training\mainapp\views.py", line 25, in wordlist
    sp = read_from_file()
  File "C:\Users\andre\PycharmProjects\xxxl\training\mainapp\views.py", line 10, in read_from_file
    file = open("training/file.txt", "r", encoding="utf-8").read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: 'training/file.txt'
"GET /words_list HTTP/1.1" 500 67124
Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\andre\PycharmProjects\xxxl\.venv\lib\site-packages\django\http\request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.0.17:8000'. You may need to add '192.168.0.17' to ALLOWED_HOSTS.
